# Generated by Django 4.2.5 on 2023-11-02 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uid', models.IntegerField(db_column='uid', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type_id', models.IntegerField(db_column='type_id', default='1')),
                ('email', models.EmailField(db_column='email', default='', max_length=255, unique=True)),
                ('user_password', models.CharField(db_column='user_password', default='', max_length=255)),
                ('first_name', models.CharField(db_column='first_name', default='', max_length=255)),
                ('last_name', models.CharField(db_column='last_name', default='', max_length=255)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=255)),
                ('state_id', models.IntegerField(db_column='state_id', default='')),
                ('promotions', models.IntegerField(db_column='promotions', default='0')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('mid', models.IntegerField(db_column='mid', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', default='', max_length=255)),
                ('cast', models.CharField(db_column='cast', default='', max_length=255)),
                ('director', models.CharField(db_column='director', default='', max_length=255)),
                ('producer', models.CharField(db_column='producer', default='', max_length=255)),
                ('synopsis', models.CharField(db_column='synopsis', default='', max_length=1027)),
                ('reviews', models.CharField(db_column='reviews', default='', max_length=1027)),
                ('trailer', models.CharField(db_column='trailer', default='', max_length=1027)),
                ('rating', models.CharField(db_column='rating', default='', max_length=255)),
                ('title', models.CharField(db_column='title', default='', max_length=255)),
                ('poster_path', models.CharField(db_column='image', default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cid', models.IntegerField(db_column='cid', primary_key=True, serialize=False)),
                ('card_type', models.CharField(db_column='card_type', default='', max_length=255)),
                ('card_number', models.IntegerField(db_column='card_number')),
                ('card_expiration', models.DateField(db_column='card_expiration')),
                ('card_street', models.CharField(db_column='card_street', default='', max_length=255)),
                ('card_city', models.CharField(db_column='card_city', default='', max_length=255)),
                ('card_state', models.CharField(db_column='card_state', default='', max_length=255)),
                ('card_zip', models.IntegerField(db_column='card_zip')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='server.customuser')),
            ],
        ),
    ]
