# Generated by Django 4.2.5 on 2023-10-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='reviews',
            field=models.CharField(default='', max_length=1027),
        ),
        migrations.AddField(
            model_name='movies',
            name='synopsis',
            field=models.CharField(default='', max_length=1027),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.CharField(default='', max_length=1027),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
