# Generated by Django 4.2.5 on 2023-11-02 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.IntegerField(db_column='uid', default=uuid.UUID('1348adf1-999b-4c9a-ba06-e1c8a15ec991'), primary_key=True, serialize=False, unique=True),
        ),
    ]
