# Generated by Django 4.2.5 on 2023-10-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_movies_cast_movies_category_movies_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='id',
            new_name='mid',
        ),
    ]
