# Generated by Django 4.2.5 on 2023-10-31 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_movies_name_movies_title_alter_movies_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(db_column='phone_number', default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promotions',
            field=models.IntegerField(db_column='promotions', default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_id',
            field=models.IntegerField(db_column='state_id', default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_id',
            field=models.IntegerField(db_column='type_id', default='1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_password',
            field=models.CharField(db_column='user_password', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_column='email', default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_column='first_name', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(db_column='uid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_column='last_name', default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cid', models.IntegerField(db_column='cid', primary_key=True, serialize=False)),
                ('card_type', models.CharField(db_column='card_type', default='', max_length=255)),
                ('card_number', models.IntegerField(db_column='card_number')),
                ('card_expiration', models.DateField(db_column='card_expiration')),
                ('card_street', models.CharField(db_column='card_street', default='', max_length=255)),
                ('card_city', models.CharField(db_column='card_city', default='', max_length=255)),
                ('card_state', models.CharField(db_column='card_state', default='', max_length=255)),
                ('card_zip', models.IntegerField(db_column='card_zip')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
