# Generated by Django 4.2.5 on 2023-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_customuser_phone_number_customuser_promotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img_link',
            field=models.CharField(db_column='Image', default='', max_length=255),
        ),
    ]
