# Generated by Django 4.2.5 on 2023-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_movies_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img_link',
            field=models.CharField(db_column='image', default='', max_length=255),
        ),
    ]
